name: compose
version: 1.4.0
usage: Compose is a helm plugin to define and manage multiple helm releases as single entity.
command: $HELM_PLUGIN_DIR/bin/compose
hooks:
  install: $HELM_PLUGIN_DIR/scripts/install.sh
  update: $HELM_PLUGIN_DIR/scripts/install.sh
